#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

# Aliyun SMS production runner.
# Secrets must be supplied by the runtime environment, not committed to git.
: "${ALIYUN_SMS_ACCESS_KEY_ID:?Set ALIYUN_SMS_ACCESS_KEY_ID}"
: "${ALIYUN_SMS_ACCESS_KEY_SECRET:?Set ALIYUN_SMS_ACCESS_KEY_SECRET}"
: "${JWT_SECRET:?Set JWT_SECRET}"
: "${SECRET_PEPPER:?Set SECRET_PEPPER}"

export SMS_PROVIDER="${SMS_PROVIDER:-aliyun}"
export ALIYUN_SMS_SIGN_NAME="${ALIYUN_SMS_SIGN_NAME:-广州浮光智能科技}"
export ALIYUN_SMS_LOGIN_TEMPLATE_CODE="${ALIYUN_SMS_LOGIN_TEMPLATE_CODE:-SMS_498805405}"
export ALIYUN_SMS_REGISTER_TEMPLATE_CODE="${ALIYUN_SMS_REGISTER_TEMPLATE_CODE:-$ALIYUN_SMS_LOGIN_TEMPLATE_CODE}"
export ALIYUN_SMS_FORGET_PASSWORD_TEMPLATE_CODE="${ALIYUN_SMS_FORGET_PASSWORD_TEMPLATE_CODE:-$ALIYUN_SMS_LOGIN_TEMPLATE_CODE}"
export ALIYUN_SMS_CODE_EXPIRE_MINUTES="${ALIYUN_SMS_CODE_EXPIRE_MINUTES:-5}"
export ALIYUN_SMS_DAILY_LIMIT="${ALIYUN_SMS_DAILY_LIMIT:-10}"
export ALIYUN_SMS_MIN_INTERVAL_SECONDS="${ALIYUN_SMS_MIN_INTERVAL_SECONDS:-60}"

exec python3 backend-api/backend_api.py --host 0.0.0.0 --port 8091
